name: Ubuntu CI

on: 
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile and test
        id: ci
        uses: gazebo-tooling/action-gz-ci@jammy
        with:
          tests-enabled: false
